language: python

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.10.0
    - LATEST_APACHE=2.4
  matrix:
    - APACHE=2.4

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - cd ./$APACHE
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$APACHE-$TRAVIS_TAG" release
    fi

    if [ "$APACHE" == "$LATEST_APACHE" ]; then
      make VERSION=latest release
    fi
  fi

after_failure:
  - make logs